['vagrant-reload'].each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    raise "Vagrant plugin #{plugin} is not installed!"
  end
end

Vagrant.configure('2') do |config|
  config.vm.box = "bento/fedora-25" # Fedora 25
  config.vm.network "private_network", ip: "192.168.50.10"

  # fix issues with slow dns https://www.virtualbox.org/ticket/13002
  #config.vm.provider "virtualbox" do |v|
  #  v.memory = 2048
  #  v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  #end

  config.vm.provider :libvirt do |libvirt|
    libvirt.connect_via_ssh = false
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.nic_model_type = "e1000"
  end

  config.ssh.forward_x11 = true

  config.vm.provision :shell, :privileged => true, :path => "setup-packages-pre-reboot.sh"
  config.vm.provision :reload
  config.vm.provision :shell, :privileged => true, :path => "setup-packages-post-reboot.sh"
  config.vm.provision :shell, :privileged => true, :path => "setup-iproute-src.sh"
end

